name: chack_chack
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.11.1


dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.2
  photo_manager: ^3.0.0

  flutter_inappwebview: ^6.1.5

  table_calendar: ^3.1.2
  intl: ^0.19.0

  flutter_riverpod: ^2.5.1

  cupertino_icons: ^1.0.8

  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:

  generate: true

  assets:
    - assets/images/e_weeklySchedule_card.png
    - assets/images/e_ownerWorkRequest_card.png
    - assets/images/e_scheduleChanged_card.png
    - assets/images/e_scheduleCompleted_card.png
    - assets/images/e_shiftRequest_card.png
    - assets/images/e_substituteRequest_card.png

    - assets/images/r_weeklySchedule_card.png
    - assets/images/r_scheduleCreationAvailable_card.png
    - assets/images/r_submissionStatus_card.png

    - assets/images/accept.png
    - assets/images/reject.png
    - assets/images/automatic_schedule_creation.png
    - assets/images/shift_complete.png
    - assets/images/substitute_complete.png


  uses-material-design: true
