name: chack_chack
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+17

environment:
  sdk: ^3.11.1


dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.2
  photo_manager: ^3.0.0

  image: ^4.2.0
  path_provider: ^2.1.0

  flutter_inappwebview: ^6.1.5

  table_calendar: ^3.1.2
  intl: ^0.19.0

  flutter_riverpod: ^2.5.1

  cupertino_icons: ^1.0.8

  shared_preferences: ^2.2.3

  http: ^1.2.1
  google_sign_in: ^6.1.5
  device_info_plus: ^11.5.0
  package_info_plus: ^8.0.0

  kakao_flutter_sdk_user: ^1.9.5

  sign_in_with_apple: ^6.1.1

  app_links: ^6.3.3
  firebase_core: ^4.11.0
  flutter_secure_storage: 10.3.1
  firebase_messaging: ^16.4.1
  flutter_svg: ^2.3.0
  flutter_markdown: ^0.7.4+3
  flutter_local_notifications: ^18.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0

  flutter_native_splash: ^2.4.1


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo/chackchack.png

  android_12:
    color: "#FFFFFF"
    image: assets/images/logo/chackchack.png


flutter:

  generate: true

  assets:
    - assets/images/e_weeklySchedule_card.png
    - assets/images/e_ownerWorkRequest_card.png
    - assets/images/e_scheduleChanged_card.png
    - assets/images/e_scheduleCompleted_card.png
    - assets/images/e_shiftRequest_card.png
    - assets/images/e_substituteRequest_card.png

    - assets/images/r_weeklySchedule_card.png
    - assets/images/r_scheduleCreationAvailable_card.png
    - assets/images/r_submissionStatus_card.png
    - assets/images/r_scheduleCollection.png

    - assets/images/accept.png
    - assets/images/reject.png
    - assets/images/automatic_schedule_creation.png
    - assets/images/shift_complete.png
    - assets/images/substitute_complete.png
    - assets/images/profile.png
    - assets/images/e_crew_invite.png
    - assets/images/pin.png

    - assets/images/onboarding/onboarding1.png
    - assets/images/onboarding/onboarding2.png
    - assets/images/onboarding/onboarding3.png
    - assets/images/onboarding/onboarding4.png

    - assets/images/logo/kakaotalk.png
    - assets/images/logo/kakao.svg
    - assets/images/logo/google.png
    - assets/images/logo/apple.png
    - assets/images/logo/chackchack.png

    - assets/images/reactions/heart.svg
    - assets/images/reactions/check.svg
    - assets/images/reactions/neutral.svg
    - assets/images/reactions/smile.svg
    - assets/images/reactions/kiss.svg
    - assets/images/reactions/proud.svg
    - assets/images/reactions/add_reaction.svg

  uses-material-design: true