// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are configured only for Android and iOS.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Q6JuOhytW_75mDl0iQzb7YlF845iRmE',
    appId: '1:16472809022:android:00096c2b708f37ab41fb6f',
    messagingSenderId: '16472809022',
    projectId: 'chack-chack-fcm',
    storageBucket: 'chack-chack-fcm.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArlNEjdY19ysedf9rd7LlB9ca0Dj1-67Y',
    appId: '1:16472809022:ios:2a070a2013294f4a41fb6f',
    messagingSenderId: '16472809022',
    projectId: 'chack-chack-fcm',
    storageBucket: 'chack-chack-fcm.firebasestorage.app',
    iosBundleId: 'com.chackchack.app',
  );
}
