// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE48FA3k3D7D_BzPTFLiuzCs0Hr8gySOk',
    appId: '1:954357709497:web:1b84e492bdeb8d4fca7968',
    messagingSenderId: '954357709497',
    projectId: 'chackchack-9fe40',
    authDomain: 'chackchack-9fe40.firebaseapp.com',
    storageBucket: 'chackchack-9fe40.firebasestorage.app',
    measurementId: 'G-T1LJ476XZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Hw41NWNp5vAYUI2tIcxy1sWWMR76wL4',
    appId: '1:954357709497:android:b2ae60e40d9ce0a4ca7968',
    messagingSenderId: '954357709497',
    projectId: 'chackchack-9fe40',
    storageBucket: 'chackchack-9fe40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCQ6UG4U3rSMC9y5eNx30mVPHL7ldkElk',
    appId: '1:954357709497:ios:9a9d001e88e90dd9ca7968',
    messagingSenderId: '954357709497',
    projectId: 'chackchack-9fe40',
    storageBucket: 'chackchack-9fe40.firebasestorage.app',
    iosBundleId: 'com.example.chackChack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCQ6UG4U3rSMC9y5eNx30mVPHL7ldkElk',
    appId: '1:954357709497:ios:9a9d001e88e90dd9ca7968',
    messagingSenderId: '954357709497',
    projectId: 'chackchack-9fe40',
    storageBucket: 'chackchack-9fe40.firebasestorage.app',
    iosBundleId: 'com.example.chackChack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE48FA3k3D7D_BzPTFLiuzCs0Hr8gySOk',
    appId: '1:954357709497:web:53c6e8be52a11a8fca7968',
    messagingSenderId: '954357709497',
    projectId: 'chackchack-9fe40',
    authDomain: 'chackchack-9fe40.firebaseapp.com',
    storageBucket: 'chackchack-9fe40.firebasestorage.app',
    measurementId: 'G-SZCVB3WB59',
  );
}
